##############################################################################
# backend-serviceaccount.yaml — IRSA ServiceAccount for DynamoDB access
##############################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-api-sa
  namespace: voting-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::541405370428:role/voting-app-backend-irsa
